@WebApi_HostAddress = http://localhost:5000
@heroId = 11111111-1111-1111-1111-111111111111

###

# Hero endpoints

### Get all heroes
GET {{WebApi_HostAddress}}/hero
Accept: application/json

###

### Get a single hero by ID
GET {{WebApi_HostAddress}}/hero/{{heroId}}
Accept: application/json

###

### Create a new hero
POST {{WebApi_HostAddress}}/hero
Content-Type: application/json

{
  "id": "{{heroId}}",
  "name": "Superman"
}

###

### Update an existing hero (ID in path must match body)
PUT {{WebApi_HostAddress}}/hero/{{heroId}}
Content-Type: application/json

{
  "id": "{{heroId}}",
  "name": "Batman"
}

###

### Delete a hero by ID
DELETE {{WebApi_HostAddress}}/hero/{{heroId}}

###
